### ISSUE TITLE
Windows and Mac are the only OSes that exist?

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LukaszWiktor/slack-status-based-on-wifi-name#3]
Linux support please

**Comment by LukaszWiktor** [comment]
One of my workmates declared to add support for Linux.

BTW How did you came across this little script? I'm curious because it has received a lot of attention today.

**Comment by TorstenCScholz** [comment]
It was posted on reddit /r/programming: https://www.reddit.com/r/programming/comments/6elz8t/set_your_status_on_slack_based_on_the_wifi/

**Comment by zeyomir** [comment]
Addressed in https://github.com/LukaszWiktor/slack-status-based-on-wifi-name/pull/4
